// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {SafeTransferLib} from '@solady/utils/SafeTransferLib.sol';

import {IERC20} from '@openzeppelin/contracts/token/ERC20/IERC20.sol';

import {IPoolManager} from '@uniswap/v4-core/src/interfaces/IPoolManager.sol';
import {Hooks, IHooks} from '@uniswap/v4-core/src/libraries/Hooks.sol';
import {SafeCast} from '@uniswap/v4-core/src/libraries/SafeCast.sol';
import {StateLibrary} from '@uniswap/v4-core/src/libraries/StateLibrary.sol';
import {TickMath} from '@uniswap/v4-core/src/libraries/TickMath.sol';
import {BalanceDelta} from '@uniswap/v4-core/src/types/BalanceDelta.sol';
import {BeforeSwapDelta, BeforeSwapDeltaLibrary, toBeforeSwapDelta} from '@uniswap/v4-core/src/types/BeforeSwapDelta.sol';

import {Currency} from '@uniswap/v4-core/src/types/Currency.sol';
import {PoolId, PoolIdLibrary} from '@uniswap/v4-core/src/types/PoolId.sol';
import {PoolKey} from '@uniswap/v4-core/src/types/PoolKey.sol';
import {ModifyLiquidityParams, SwapParams} from '@uniswap/v4-core/src/types/PoolOperation.sol';

import {FeeDistributor} from '@flaunch/hooks/FeeDistributor.sol';
import {Notifier} from '@flaunch/hooks/Notifier.sol';
import {UnlockingHook} from '@flaunch/hooks/UnlockingHook.sol';
import {CurrencySettler} from '@flaunch/libraries/CurrencySettler.sol';
import {FlaunchLibrary} from '@flaunch/libraries/FlaunchLibrary.sol';
import {TokenSupply} from '@flaunch/libraries/TokenSupply.sol';
import {UniswapHookEvents} from '@flaunch/libraries/UniswapHookEvents.sol';
import {TreasuryActionManager} from '@flaunch/treasury/ActionManager.sol';
import {MemecoinTreasury} from '@flaunch/treasury/MemecoinTreasury.sol';
import {MemecoinFinder} from '@flaunch/types/MemecoinFinder.sol';
import {StoreKeys} from '@flaunch/types/StoreKeys.sol';

import {IBidWall} from '@flaunch-interfaces/IBidWall.sol';
import {IFLETH} from '@flaunch-interfaces/IFLETH.sol';
import {IFeeCalculator} from '@flaunch-interfaces/IFeeCalculator.sol';
import {IFeeExemptions} from '@flaunch-interfaces/IFeeExemptions.sol';
import {IFlaunch} from '@flaunch-interfaces/IFlaunch.sol';
import {IInitialPrice} from '@flaunch-interfaces/IInitialPrice.sol';
import {IInternalSwapPool} from '@flaunch-interfaces/IInternalSwapPool.sol';
import {IMemecoin} from '@flaunch-interfaces/IMemecoin.sol';
import {IOracle} from '@flaunch-interfaces/IOracle.sol';
import {IPositionManager} from '@flaunch-interfaces/IPositionManager.sol';

/**
 * The PositionManager is a Uniswap V4 hook that controls the user journey from token creation
 * to ongoing swaps.
 *
 * The creator of the pool will receive an ERC721 representation of the token. The holder of
 * this token will be the recipient of any creator fees generated by the token in the pool.
 *
 * Hook interactions have aimed to be abstracted into inherited contracts to simplify both
 * functionality and readability. Specific use of each of these contracts has been denoted
 * within comments using square brackets where possible.
 */
contract PositionManager is UnlockingHook, FeeDistributor, IPositionManager, StoreKeys {
    using BeforeSwapDeltaLibrary for BeforeSwapDelta;
    using CurrencySettler for Currency;
    using PoolIdLibrary for PoolKey;
    using SafeCast for uint;
    using StateLibrary for IPoolManager;
    using MemecoinFinder for PoolKey;

    /// Identifies the action a {PoolManager} `unlock` callback should perform
    enum UnlockCallbackType {
        CLOSE_BIDWALL,
        FLAUNCH_LIQUIDITY
    }

    /// The minimum amount before a distribution is triggered
    uint public constant MIN_DISTRIBUTE_THRESHOLD = 0.001 ether;

    /// The contract that will be used for flaunching tokens
    IFlaunch public flaunchContract;

    /// Our starting token sqrtPriceX96
    IInitialPrice public initialPrice;

    /// Internal storage to allow the `beforeSwap` tick value to be used in `afterSwap`
    int24 internal _beforeSwapTick;

    /// Store the address that will collect protocol fees
    address internal protocolFeeRecipient;

    /// Store the contract that will manage our Bidwall interactions
    IBidWall public bidWall;

    /// The contract that handles the token Treasury actions
    TreasuryActionManager public actionManager;

    /// Store the contract that will manage fee exemptions
    IFeeExemptions public feeExemptions;

    /// Store our {Notifier} contract
    Notifier public notifier;

    /// The price {Oracle} used to price internal fills
    IOracle public immutable oracle;

    /// The shared {InternalSwapPool} that holds fee inventory + the price oracle for our pools
    IInternalSwapPool public internalSwapPool;

    /// Store the block timestamp when a poolId is set to launch
    mapping(PoolId _poolId => uint _flaunchTime) public flaunchesAt;

    /// Stores the tick the pool was initialized at, captured from `poolManager.initialize`. Used
    /// by fee calculators (e.g. {TrustedSignerFeeCalculator}) to quote against the launch price
    mapping(PoolId _poolId => int24 _initialTick) public initialPoolTick;

    /**
     * Initializes our {BaseHook} contract and initializes all implemented hooks.
     */
    constructor(
        ConstructorParams memory params
    )
        UnlockingHook(params.poolManager)
        FeeDistributor(params.nativeToken, params.feeDistribution, params.protocolOwner, params.flayGovernance, params.feeEscrow)
    {
        // Set our contract references
        initialPrice = params.initialPrice;

        // Set our protocol fee recipient
        protocolFeeRecipient = params.protocolFeeRecipient;

        // Register our FeeExemption contract
        feeExemptions = params.feeExemptions;

        // Register our BidWall contract
        bidWall = params.bidWall;

        // Register our ActionManager
        actionManager = TreasuryActionManager(address(params.actionManager));

        // Register our shared InternalSwapPool
        internalSwapPool = params.internalSwapPool;

        // Register our shared price Oracle
        oracle = params.oracle;

        // Deploy our notifier
        notifier = new Notifier(params.protocolOwner);

        // Approve the BidWall to manage native token from the PositionManager
        IERC20(params.nativeToken).approve(address(bidWall), type(uint).max);
    }

    /**
     * Creates a new ERC20 memecoin token creating and an ERC721 that signifies ownership of the
     * flaunched collection. The token is then initialized into a UV4 pool.
     *
     * @param _params The parameters for the flaunch
     *
     * @return memecoin_ The created ERC20 token address
     */
    function flaunch(
        FlaunchParams calldata _params
    ) external payable returns (address memecoin_) {
        uint tokenId;
        address payable memecoinTreasury;
        PoolId poolId;
        bool currencyFlipped;

        // Flaunch our token to create the memecoin and memecoin treasury
        (memecoin_, memecoinTreasury, tokenId) = flaunchContract.flaunch(_params);

        // Check if we have an initial flaunching fee, check that enough ETH has been sent
        uint flaunchFee = getFlaunchingFee(_params.initialPriceParams);

        uint remainingValue = msg.value;

        // Collect the launch fee first.
        if (flaunchFee != 0) {
            if (remainingValue < flaunchFee) {
                revert InsufficientFlaunchFee(remainingValue, flaunchFee);
            }

            remainingValue -= flaunchFee;

            // Transfer the flaunching fee to the protocol fee recipient
            SafeTransferLib.safeTransferETH(protocolFeeRecipient, flaunchFee);
        }

        // Initialize the pool and store the pool key and currency flipped
        (poolId, currencyFlipped) = _initializeLaunchedPool(memecoin_, memecoinTreasury, _params);

        emit PoolCreated({
            _poolId: poolId,
            _memecoin: memecoin_,
            _memecoinTreasury: memecoinTreasury,
            _tokenId: tokenId,
            _currencyFlipped: currencyFlipped,
            _flaunchFee: flaunchFee,
            _params: _params
        });

        // Seed the pool's initial single-sided liquidity (and fill the premine, if any) inside a
        // {PoolManager} unlock, as creating positions requires the unlock context. We also process
        // any premine / prebuy calculations inside of this unlock callback.
        remainingValue -= abi.decode(
            poolManager.unlock(
                abi.encode(
                    UnlockCallbackType.FLAUNCH_LIQUIDITY, abi.encode(memecoin_, _params.creator, _params.premineAmount, remainingValue)
                )
            ),
            (uint)
        );

        // Refund any remaining ETH that was not required
        if (remainingValue != 0) {
            SafeTransferLib.safeTransferETH(msg.sender, remainingValue);
        }

        // After our contract is initialized, emit our pool state update to notify the UX of
        // current prices and fees.
        _emitPoolStateUpdate(poolId, IHooks.afterInitialize.selector, abi.encode(tokenId, _params));
    }

    /**
     * Initializes the pool for a launched memecoin.
     *
     * @param _memecoin The address of the memecoin
     * @param _memecoinTreasury The address of the memecoin treasury
     * @param _params The parameters for the flaunch
     *
     * @return poolId_ The ID of the pool
     * @return currencyFlipped_ Whether the currency is flipped
     */
    function _initializeLaunchedPool(
        address _memecoin,
        address payable _memecoinTreasury,
        FlaunchParams calldata _params
    ) internal returns (PoolId poolId_, bool currencyFlipped_) {
        // Determine if the currency is flipped
        currencyFlipped_ = nativeToken >= _memecoin;

        // Create the pool key
        PoolKey memory poolKey_ = PoolKey({
            currency0: Currency.wrap(!currencyFlipped_ ? nativeToken : _memecoin),
            currency1: Currency.wrap(currencyFlipped_ ? nativeToken : _memecoin),
            fee: 0,
            tickSpacing: 60,
            hooks: IHooks(address(this))
        });

        // Initialize the memecoin treasury
        MemecoinTreasury(_memecoinTreasury).initialize(payable(address(this)), address(actionManager), nativeToken, poolKey_);

        // Store the pool key
        _poolKeys[_memecoin] = poolKey_;

        // Store the pool ID
        poolId_ = poolKey_.toId();

        // If the token is scheduled to flaunch in the future, store the timestamp so that
        // `_beforeSwap` can gate public swaps until the schedule has passed. A premine is
        // exempt from this as it is filled internally during `flaunch`, not via `_beforeSwap`.
        if (_params.flaunchAt > block.timestamp) {
            flaunchesAt[poolId_] = _params.flaunchAt;
            emit PoolScheduled(poolId_, _params.flaunchAt);
        }

        // Store the creator fee allocation
        if (_params.creatorFeeAllocation != 0) {
            creatorFee[poolId_] = _params.creatorFeeAllocation;
        }

        // Initialize the pool at its starting price and cache the resulting tick so fee
        // calculators can later quote swaps against the launch price
        initialPoolTick[poolId_] =
            poolManager.initialize(poolKey_, initialPrice.getSqrtPriceX96(msg.sender, currencyFlipped_, _params.initialPriceParams));

        // [F-7] Seed the price Oracle's ring buffer with the initial tick so that the very first
        // {InternalSwapPool} fill (and any other TWAP consumer) is priced from oracle history,
        // never from slot0. Without this seed, the `twapTick()` warm-up branch returns the spot
        // tick on the first observation, which can be moved atomically within the same swap.
        oracle.recordObservation(poolId_, initialPoolTick[poolId_]);

        // Initialize the fee calculators
        _initializeFeeCalculators(poolId_, _params.feeCalculatorParams);
    }

    /**
     * Returns the PoolKey mapped to the token address. If none is set then a zero value
     * will be returned for the fields.
     *
     * @dev The easiest way to check for an empty response is `tickSpacing = 0`
     *
     * @param _token The address of the ERC20 token
     *
     * @return The corresponding {PoolKey} for the token
     */
    function poolKey(
        address _token
    ) external view returns (PoolKey memory) {
        return _poolKeys[_token];
    }

    /**
     * Pass-through getter for a pool's {InternalSwapPool} claimable fees, kept on the
     * {PositionManager} for integrations that previously read fees directly from the hook.
     *
     * @param _poolKey The PoolKey to check
     */
    function poolFees(
        PoolKey memory _poolKey
    ) external view returns (IInternalSwapPool.ClaimableFees memory) {
        return internalSwapPool.poolFees(_poolKey);
    }

    /**
     * Defines the Uniswap V4 hooks that are used by our implementation. This will determine
     * the address that our contract **must** be deployed to for Uniswap V4. This address suffix
     * is shown in the dev comments for this function call.
     *
     * @dev 10 0101 1101 1100 == 25DC
     */
    function getHookPermissions() public pure override returns (Hooks.Permissions memory) {
        return Hooks.Permissions({
            beforeInitialize: true, // Prevent initialize
            afterInitialize: false,
            beforeAddLiquidity: false,
            afterAddLiquidity: true, // [EventTracking]
            beforeRemoveLiquidity: false,
            afterRemoveLiquidity: true, // [EventTracking]
            beforeSwap: true, // [InternalSwapPool]
            afterSwap: true, // [FeeDistributor], [InternalSwapPool], [BidWall], [EventTracking]
            beforeDonate: false,
            afterDonate: true, // [EventTracking]
            beforeSwapReturnDelta: true, // [InternalSwapPool]
            afterSwapReturnDelta: true, // [FeeDistributor]
            afterAddLiquidityReturnDelta: false,
            afterRemoveLiquidityReturnDelta: false
        });
    }

    /**
     * The hook called before the state of a pool is initialized. Prevents external contracts
     * from initializing pools using our contract as a hook.
     *
     * @dev As we call `poolManager.initialize` from the IHooks contract itself, we bypass this
     * hook call as therefore bypass the prevention.
     */
    function _beforeInitialize(
        address,
        PoolKey calldata,
        uint160
    ) internal pure override returns (bytes4) {
        revert CannotBeInitializedDirectly();
    }

    /**
     * [ISP] Checks if we can process an internal swap ahead of the Uniswap swap.
     * [FD] Captures fees from the internal swap pool
     *
     * @param _sender The address calling the swap
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     *
     * @return selector_ The function selector for the hook
     * @return beforeSwapDelta_ The hook's delta in specified and unspecified currencies. Positive: the hook is
     * owed/took currency, negative: the hook owes/sent currency
     * @return swapFee_ The percentage fee applied to our swap
     */
    function _beforeSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        bytes calldata _hookData
    ) internal override returns (bytes4 selector_, BeforeSwapDelta beforeSwapDelta_, uint24) {
        PoolId poolId = _key.toId();

        /**
         * [SCHEDULE] Check if the token is scheduled to be flaunched.
         */

        // If set, get the timestamp that the pool is scheduled to flaunch
        uint _flaunchesAt = flaunchesAt[poolId];
        if (_flaunchesAt != 0) {
            // If we have a schedule set for the token, then we need to make an additional
            // check to see if a premine is set, and if it's valid. If the timestamp has not
            // yet passed, then we revert.
            if (_flaunchesAt > block.timestamp) {
                revert TokenNotFlaunched(_flaunchesAt);
            }

            // Remove the schedule timestamp to prevent future checks
            delete flaunchesAt[poolId];
        }

        bool nativeIsZero = nativeToken == Currency.unwrap(_key.currency0);

        /**
         * [ISP] We want to see if we have any token1 fee tokens that we can use to fill the swap
         * before it hits the Uniswap pool. This prevents the pool from being affected and reduced
         * gas costs. This also allows us to benefit from the Uniswap routing infrastructure.
         *
         * This frontruns Uniswap to sell undesired token amounts from our fees into desired tokens
         * ahead of our fee distribution. This acts as a partial orderbook to remove impact against
         * our pool.
         */
        beforeSwapDelta_ = _processInternalSwap(_sender, _key, _params, _hookData, nativeIsZero, beforeSwapDelta_);

        // Capture the beforeSwap tick value before actioning our Uniswap swap
        (, _beforeSwapTick,,) = poolManager.getSlot0(poolId);

        // Check if the BidWall has become stale, and allow liquidity to be extracted before a
        // threshold has been built.
        bidWall.checkStalePosition(_key, _beforeSwapTick, nativeIsZero);

        // Record the pre-swap tick into the price oracle (at most once per block) on every swap,
        // regardless of direction or inventory, so the TWAP reference stays fresh.
        oracle.recordObservation(poolId, _beforeSwapTick);

        // Set our return selector
        selector_ = IHooks.beforeSwap.selector;
    }

    /**
     * Helper that runs the InternalSwapPool fast-path during `_beforeSwap`. Extracted to keep the
     * outer hook function below the legacy stack-too-deep threshold.
     *
     * @param _sender The address calling the swap
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     * @param _nativeIsZero Whether the native token is zero
     * @param _beforeSwapDelta The before swap delta
     *
     * @return beforeSwapDelta_ The before swap delta
     */
    function _processInternalSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        bytes calldata _hookData,
        bool _nativeIsZero,
        BeforeSwapDelta _beforeSwapDelta
    ) internal returns (BeforeSwapDelta beforeSwapDelta_) {
        beforeSwapDelta_ = _beforeSwapDelta;

        (uint tokenIn, uint tokenOut) = internalSwapPool.internalSwap(_key, _params, _nativeIsZero);
        if (tokenIn + tokenOut == 0) {
            return beforeSwapDelta_;
        }

        // The {InternalSwapPool} computed the fill against its fee inventory but, as the swap-delta
        // owner, this hook performs the matching settlement: take the native `tokenIn` from the
        // {PoolManager} and settle the memecoin `tokenOut` back into it.
        poolManager.take(_nativeIsZero ? _key.currency0 : _key.currency1, address(this), tokenIn);
        (_nativeIsZero ? _key.currency1 : _key.currency0).settle(poolManager, address(this), tokenOut, false);

        BeforeSwapDelta internalBeforeSwapDelta = _params.amountSpecified >= 0
            ? toBeforeSwapDelta(-tokenOut.toInt128(), tokenIn.toInt128())
            : toBeforeSwapDelta(tokenIn.toInt128(), -tokenOut.toInt128());

        uint swapFee = _captureAndDepositFees(_key, _params, _sender, internalBeforeSwapDelta.getUnspecifiedDelta(), _hookData);

        _captureDelta(_params, TS_ISP_AMOUNT0, TS_ISP_AMOUNT1, internalBeforeSwapDelta);
        _captureDeltaSwapFee(_params, TS_ISP_FEE0, TS_ISP_FEE1, swapFee);

        beforeSwapDelta_ = toBeforeSwapDelta(
            beforeSwapDelta_.getSpecifiedDelta() + internalBeforeSwapDelta.getSpecifiedDelta(),
            beforeSwapDelta_.getUnspecifiedDelta() + internalBeforeSwapDelta.getUnspecifiedDelta() + swapFee.toInt128()
        );
    }

    /**
     * [FD] Captures fees from the swap to either distribute or send to ISP
     * [ISP] Once a swap has been made, we distribute fees to our LPs and emit our price update event.
     * [FD] Tracks the swap for future fee calculations
     *
     * @param _sender The sender (or swap contract) making the call
     * @param _key The key for the pool
     * @param _params The parameters for the swap
     * @param _delta The amount owed to the caller (positive) or owed to the pool (negative)
     * @param _hookData Arbitrary data handed into the PoolManager by the swapper to be be passed on to the hook
     *
     * @return selector_ The function selector for the hook
     * @return hookDeltaUnspecified_ The hook's delta in unspecified currency. Positive: the hook is owed/took currency,
     * negative: the hook owes/sent currency
     */
    function _afterSwap(
        address _sender,
        PoolKey calldata _key,
        SwapParams calldata _params,
        BalanceDelta _delta,
        bytes calldata _hookData
    ) internal override returns (bytes4 selector_, int128 hookDeltaUnspecified_) {
        /**
         * [FD] We need to determine the amount of fees generated by our Uniswap swap to capture,
         * rather than sending the full amount to the end user.
         */

        // Determine the currency that we will be taking our fee from
        (int128 amount0, int128 amount1) = (_delta.amount0(), _delta.amount1());
        int128 swapAmount = _params.amountSpecified < 0 == _params.zeroForOne ? amount1 : amount0;

        // Capture the swap fees and dispatch the referrer's share if set
        uint swapFee = _captureAndDepositFees(_key, _params, _sender, swapAmount, _hookData);

        // Increment our swap
        assembly {
            tstore(TS_UNI_AMOUNT0, amount0)
            tstore(TS_UNI_AMOUNT1, amount1)
        }

        _captureDeltaSwapFee(_params, TS_UNI_FEE0, TS_UNI_FEE1, swapFee);

        /**
         * [ISP] Distribute any fees that have been converted by the swap.
         */
        _distributeFees(_key);

        /**
         * [FD] If we have a feeCalculator, then we want to track the swap data for any
         * dynamic calculations.
         */
        PoolId poolId = _key.toId();

        {
            IFeeCalculator _feeCalculator = feeCalculator;
            if (address(_feeCalculator) != address(0)) {
                _feeCalculator.trackSwap(_sender, _key, _params, _delta, _hookData);
            }
        }

        // Set our return selector
        hookDeltaUnspecified_ = swapFee.toInt128();

        selector_ = IHooks.afterSwap.selector;

        // Emit our compiled swap data
        _emitSwapUpdate(poolId, _sender);

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(poolId, selector_, abi.encode(_sender, _params, _delta));
    }

    /**
     * Once a liquidity has been added, we emit our price update event.
     *
     * @param _sender The initial msg.sender for the add liquidity call
     * @param _key The key for the pool
     * @param _delta The caller's balance delta after adding liquidity; the sum of principal delta, fees accrued, and
     * hook delta
     * @param _feesAccrued The fees accrued since the last time fees were collected from this position
     *
     * @return selector_ The function selector for the hook
     * @return BalanceDelta The hook's delta in token0 and token1. Positive: the hook is owed/took currency, negative:
     * the hook owes/sent currency
     */
    function _afterAddLiquidity(
        address _sender,
        PoolKey calldata _key,
        ModifyLiquidityParams calldata,
        BalanceDelta _delta,
        BalanceDelta _feesAccrued,
        bytes calldata
    ) internal override returns (bytes4 selector_, BalanceDelta) {
        selector_ = IHooks.afterAddLiquidity.selector;

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(_key.toId(), selector_, abi.encode(_sender, _delta, _feesAccrued));
    }

    /**
     * Once liquidity has been removed, we emit our price update event.
     *
     * @param _sender The initial msg.sender for the remove liquidity call
     * @param _key The key for the pool
     * @param _delta The caller's balance delta after removing liquidity; the sum of principal delta, fees accrued, and
     * hook delta
     * @param _feesAccrued The fees accrued since the last time fees were collected from this position
     *
     * @return selector_ The function selector for the hook
     */
    function _afterRemoveLiquidity(
        address _sender,
        PoolKey calldata _key,
        ModifyLiquidityParams calldata,
        BalanceDelta _delta,
        BalanceDelta _feesAccrued,
        bytes calldata
    ) internal override returns (bytes4 selector_, BalanceDelta) {
        selector_ = IHooks.afterRemoveLiquidity.selector;

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(_key.toId(), selector_, abi.encode(_sender, _delta, _feesAccrued));
    }

    /**
     * The hook called after donate, emitting our price update event.
     *
     * @param _sender The initial msg.sender for the donate call
     * @param _key The key for the pool
     * @param _amount0 The amount of token0 being donated
     * @param _amount1 The amount of token1 being donated
     *
     * @return selector_ The function selector for the hook
     */
    function _afterDonate(
        address _sender,
        PoolKey calldata _key,
        uint _amount0,
        uint _amount1,
        bytes calldata
    ) internal override returns (bytes4 selector_) {
        selector_ = IHooks.afterDonate.selector;

        // Emit our pool state update to listeners
        _emitPoolStateUpdate(_key.toId(), selector_, abi.encode(_sender, _amount0, _amount1));
    }

    /**
     * Gets the ETH fee that must be paid to flaunch a token.
     *
     * @return The ETH value of the fee
     */
    function getFlaunchingFee(
        bytes calldata _initialPriceParams
    ) public view returns (uint) {
        return initialPrice.getFlaunchingFee(msg.sender, _initialPriceParams);
    }

    /**
     * Gets the ETH market cap for a new token that will be flaunched.
     *
     * @return The ETH market cap value
     */
    function getFlaunchingMarketCap(
        bytes calldata _initialPriceParams
    ) public view returns (uint) {
        return initialPrice.getMarketCap(_initialPriceParams);
    }

    /**
     * Allows the contract used to flaunch a new token to be updated.
     *
     * @param _flaunchContract The new {IFlaunch} contract address
     */
    function setFlaunch(
        address _flaunchContract
    ) public onlyOwner {
        flaunchContract = IFlaunch(_flaunchContract);
    }

    /**
     * Updates the `IInitialPrice` contract address that is used during `flaunch` to calculate
     * the initial tick / sqrtPriceX96 value.
     *
     * @param _initialPrice The contract address for the `IInitialPrice` contract
     */
    function setInitialPrice(
        address _initialPrice
    ) public onlyOwner {
        initialPrice = IInitialPrice(_initialPrice);
        emit InitialPriceUpdated(_initialPrice);
    }

    /**
     * Calls for the BidWall to be closed, as this requires callback from the {PoolManager}.
     */
    function closeBidWall(
        PoolKey memory _key
    ) public {
        // Ensure that the call is made by the BidWall which validates logic
        if (msg.sender != address(bidWall)) {
            revert CallerIsNotBidWall();
        }

        // Ensure that the PoolKey that is being closed is valid and recognised on the protocol,
        // otherwise we could processing issues and false positives in upcoming steps. We need to
        // ensure that the PoolKey is recognised (by checking the hooks address is not zero) and
        // that the PoolId matches when encoded.
        PoolKey memory storedKey = _poolKeys[address(_key.memecoin(nativeToken))];
        if (storedKey.hooks == IHooks(address(0)) || PoolId.unwrap(storedKey.toId()) != PoolId.unwrap(_key.toId())) {
            revert UnknownPool(_key.toId());
        }

        // Action our BidWall closure via the {PoolManager} unlock
        _closeBidWall(_key);
    }

    /**
     * Unwinds the BidWall position for a pool via a {PoolManager} unlock.
     *
     * @dev The caller is responsible for validating the `PoolKey` before this is reached.
     *
     * @param _poolKey The PoolKey to close the BidWall of
     */
    function _closeBidWall(
        PoolKey memory _poolKey
    ) internal override {
        poolManager.unlock(abi.encode(UnlockCallbackType.CLOSE_BIDWALL, abi.encode(_poolKey)));
    }

    /**
     * Handles the unlock callback for the {PoolManager} interactions.
     *
     * @param _data The encoded data for the unlock callback
     *
     * @return bytes The data to be returned from the unlock callback
     */
    function _unlockCallback(
        bytes calldata _data
    ) internal override returns (bytes memory) {
        // Decode the data to determine the action and payload
        (UnlockCallbackType _action, bytes memory _payload) = abi.decode(_data, (UnlockCallbackType, bytes));

        // Check if we are closing the BidWall
        if (_action == UnlockCallbackType.CLOSE_BIDWALL) {
            bidWall.closeBidWall(abi.decode(_payload, (PoolKey)));
            return '';
        }
        // Check if we are seeding the liquidity and premine
        else if (_action == UnlockCallbackType.FLAUNCH_LIQUIDITY) {
            return _seedLiquidityAndPremine(_payload);
        }

        // Return empty data if we haven't matched any of the actions
        return '';
    }

    /**
     * Seeds a freshly flaunched pool with its initial single-sided liquidity and, if requested,
     * fills a premine for the creator. Runs inside the {PoolManager} unlock context.
     *
     * The full token supply is held by this contract following the flaunch. We seed the supply as
     * a single-sided memecoin sell position and, if a premine was requested, swap against that
     * position to deliver the premined tokens to the creator. Any flETH we wrapped but did not end
     * up spending on the premine is unwrapped back into ETH so {flaunch} can refund the caller.
     *
     * @param _payload ABI-encoded `(address memecoin, address creator, uint premineAmount, uint remainingValue)`
     *
     * @return amountSpent_ ABI-encoded amount of ETH consumed by the premine swap
     */
    function _seedLiquidityAndPremine(
        bytes memory _payload
    ) internal returns (bytes memory amountSpent_) {
        // Decode the payload to provide the required information
        (address memecoin, address creator, uint premineAmount, uint remainingValue) = abi.decode(_payload, (address, address, uint, uint));

        // Resolve the pool key and determine if the native token is the zero token
        PoolKey memory _poolKey = _poolKeys[memecoin];
        bool nativeIsZero = nativeToken == Currency.unwrap(_poolKey.currency0);

        // Seed the single-sided memecoin sell position with the remaining supply. The tick locals
        // are scoped so they fall off the stack before the premine branch runs.
        {
            int24 initialTick = initialPoolTick[_poolKey.toId()];
            (,, int24 memeTickLower, int24 memeTickUpper) = FlaunchLibrary.launchTickRanges(initialTick, nativeIsZero);

            FlaunchLibrary.createImmutablePosition({
                _poolManager: poolManager,
                _poolKey: _poolKey,
                _tickLower: memeTickLower,
                _tickUpper: memeTickUpper,
                _tokens: TokenSupply.INITIAL_SUPPLY,
                _tokenIsZero: !nativeIsZero
            });
        }

        // Fill the premine if any has been requested. Extracted into a helper so the swap-side
        // locals don't share a stack frame with the seeder above (avoids stack-too-deep).
        uint spent;
        if (premineAmount != 0) {
            spent = _executePremine(_poolKey, nativeIsZero, memecoin, creator, premineAmount, remainingValue);
        }

        amountSpent_ = abi.encode(spent);
    }

    /**
     * Executes the premine swap against the just-seeded liquidity, settles the flETH owed,
     * forwards the premined memecoin to the creator, and unwraps any unused flETH so the
     * caller can refund the excess.
     */
    function _executePremine(
        PoolKey memory _poolKey,
        bool _nativeIsZero,
        address _memecoin,
        address _creator,
        uint _premineAmount,
        uint _remainingValue
    ) private returns (uint spent_) {
        // Wrap all the remaining ETH into flETH up front so it is available as the swap input.
        // We may not consume all of it; the unused portion is unwrapped below.
        IFLETH(nativeToken).deposit{value: _remainingValue}(0);

        // Action a swap against the liquidity that has just been added to the pool. We cannot
        // be front-run in this step as we are adding liquidity inside this transaction.
        // The premine pays native and receives memecoin: when native is currency0 we swap
        // 0 -> 1 (zeroForOne=true) with the low-side price limit; otherwise we swap 1 -> 0
        // with the high-side price limit.
        BalanceDelta delta = poolManager.swap(
            _poolKey,
            SwapParams({
                zeroForOne: _nativeIsZero,
                amountSpecified: int(_premineAmount),
                sqrtPriceLimitX96: _nativeIsZero ? TickMath.MIN_SQRT_PRICE + 1 : TickMath.MAX_SQRT_PRICE - 1
            }),
            ''
        );

        // The native-side delta is negative and represents the flETH the pool is owed. Capture
        // the absolute value as `spent_` so we can both settle the debt and compute the refund.
        (Currency nativeCurrency, Currency memecoinCurrency, int128 nativeDelta) = _nativeIsZero
            ? (_poolKey.currency0, _poolKey.currency1, delta.amount0())
            : (_poolKey.currency1, _poolKey.currency0, delta.amount1());
        spent_ = uint(-int(nativeDelta));

        // If we have spent more than the remaining value, then we will need to revert
        if (spent_ > _remainingValue) {
            revert InsufficientPreminePayment(spent_, _remainingValue);
        }

        // Settle the flETH owed for the premine and take the premined memecoin
        nativeCurrency.settle(poolManager, address(this), spent_, false);
        poolManager.take(memecoinCurrency, address(this), _premineAmount);

        // Unwrap any unused flETH back to ETH so {flaunch} can refund the caller
        uint unused = _remainingValue - spent_;
        if (unused != 0) {
            IFLETH(nativeToken).withdraw(unused);
        }

        // Send the premined tokens directly to the creator
        IERC20(_memecoin).transfer(_creator, _premineAmount);
    }

    /**
     * Capture the fees from our swap. This could either be from an internal swap (`beforeSwap`)
     * or from the actual Uniswap swap (`afterSwap`).
     *
     * @dev This is only used due to too many variables in the `beforeSwap` function
     *
     * @param _key The {PoolKey} that the swap was made against
     * @param _params The swap parameters called in the swap
     * @param _sender The sender of the swap call
     * @param _delta The balance change from the swap
     * @param _hookData Additional bytes data passed in the swap
     *
     * @return swapFee_ The fee taken from the swap
     */
    function _captureAndDepositFees(
        PoolKey calldata _key,
        SwapParams memory _params,
        address _sender,
        int128 _delta,
        bytes calldata _hookData
    ) internal returns (uint swapFee_) {
        // Determine the swap fee currency based on swap parameters
        Currency swapFeeCurrency = _params.amountSpecified < 0 == _params.zeroForOne ? _key.currency1 : _key.currency0;

        // Capture our swap fees amount
        swapFee_ = _captureSwapFees({
            _poolManager: poolManager,
            _key: _key,
            _params: _params,
            _feeCalculator: feeCalculator,
            _swapFeeCurrency: swapFeeCurrency,
            _swapAmount: uint128(_delta < 0 ? -_delta : _delta),
            _feeExemption: feeExemptions.feeExemption(_sender)
        });

        // If we have no swap fees, then we have nothing to process
        if (swapFee_ == 0) {
            return swapFee_;
        }

        // Check if we have a referrer set and send them the currency directly
        uint referrerFee =
            _distributeReferrerFees({_key: _key, _swapFeeCurrency: swapFeeCurrency, _swapFee: swapFee_, _hookData: _hookData});

        // Deposit the remaining fees against our pool to be either distributed to
        // others, or placed into the Internal Swap Pool to be converted into an ETH
        // equivalent token. We don't reduce the amount by referrer fees as we still
        // need to claim this from the PoolManager.
        internalSwapPool.depositFees(
            _key,
            Currency.unwrap(swapFeeCurrency) == nativeToken ? swapFee_ - referrerFee : 0,
            Currency.unwrap(swapFeeCurrency) == nativeToken ? 0 : swapFee_ - referrerFee
        );
    }

    /**
     * We want to be able to distribute fees across our {FeeDistribution} recipients
     * when we reach a set threshold. This will only ever distribute the ETH equivalent
     * token, as the non-ETH token will be converted via the {InternalSwapPool} hook logic.
     *
     * @dev There referrer has already received their share, so they do not need to be
     * taken into account at this point.
     *
     * @param _poolKey The PoolKey reference that will have fees distributed
     */
    function _distributeFees(
        PoolKey memory _poolKey
    ) internal {
        PoolId poolId = _poolKey.toId();

        // Get the amount of the native token available to distribute
        uint distributeAmount = internalSwapPool.poolFees(_poolKey).amount0;

        // Ensure that the collection has sufficient fees available
        if (distributeAmount < MIN_DISTRIBUTE_THRESHOLD) {
            return;
        }

        // Reduce our available fees for the pool
        internalSwapPool.resetNativeFees(poolId);

        // Find the distribution amount across our different users. The amount that treasury
        // receives will be determined by variables throughout the distribution flow, such as
        // the BidWall being disabled, etc.
        (uint bidWallFee, uint creatorFee, uint protocolFee) = feeSplit(poolId, distributeAmount);
        uint treasuryFee;

        // Load our memecoin so that we can query the creator and treasury
        IMemecoin memecoin = _poolKey.memecoin(nativeToken);

        // [F-9] The Flaunch NFT is a bearer instrument: whoever holds it right now is the
        // creator that fees should route to. Read `memecoin.creator()` live at each decision
        // point rather than caching once across external calls. Defends against any future
        // call-path that could change ownership between branches (e.g. an ERC721 receiver
        // hook on a buyer's transferFrom callback flipping the NFT mid-distribution).

        if (creatorFee != 0) {
            address creatorNow = _memecoinCreator(address(memecoin));
            // Ensure that the pool creator has not burned their ownership and send them the fees
            if (creatorNow != address(0)) {
                _allocateFees(poolId, creatorNow, creatorFee);
            }
            // If the pool creator has burned their ownership, then we instead send fees directly
            // to the BidWall.
            else {
                bidWallFee += creatorFee;
                creatorFee = 0;
            }
        }

        if (bidWallFee != 0) {
            // Check if we have an active BidWall for the pool. If we don't have an active BidWall, then
            // we will need to instead allocate this to the protocol.
            if (bidWall.isBidWallEnabled(poolId)) {
                // Otherwise, we can deposit directly into the BidWall as we have permission to modify
                // liquidity outside of the window.
                bidWall.deposit(_poolKey, bidWallFee, _beforeSwapTick, nativeToken == Currency.unwrap(_poolKey.currency0));
            } else {
                // If we cannot import into BidWall, then treasury will be allocated the fees
                treasuryFee += bidWallFee;
                bidWallFee = 0;
            }
        }

        if (treasuryFee != 0) {
            // Re-read the live creator to settle the treasury branch: a burn that happens
            // between the creator-fee allocation and here must route through to the protocol.
            if (_memecoinCreator(address(memecoin)) != address(0)) {
                _allocateFees(poolId, memecoin.treasury(), treasuryFee);
            } else {
                // If we cannot allocate to treasury, then protocol receives the fees
                protocolFee += treasuryFee;
                treasuryFee = 0;
            }
        }

        // Finally we allocate our protocol fees
        if (protocolFee != 0) {
            _allocateFees(poolId, protocolFeeRecipient, protocolFee);
        }

        emit PoolFeesDistributed(poolId, distributeAmount, creatorFee, bidWallFee, treasuryFee, protocolFee);
    }

    /**
     * Using the `tstore` values that we have generated along the way, we emit an event that shows
     * the breakdown of fees earned at each swap point.
     *
     * @param _poolId The PoolId that is being emitted
     * @param _sender The router of the swap
     */
    function _emitSwapUpdate(
        PoolId _poolId,
        address _sender
    ) internal {
        // Emit our protocol-recognised event
        emit PoolSwap(
            _poolId,
            0,
            0,
            0,
            0,
            _tload(TS_ISP_AMOUNT0),
            _tload(TS_ISP_AMOUNT1),
            _tload(TS_ISP_FEE0),
            _tload(TS_ISP_FEE1),
            _tload(TS_UNI_AMOUNT0),
            _tload(TS_UNI_AMOUNT1),
            _tload(TS_UNI_FEE0),
            _tload(TS_UNI_FEE1)
        );

        // Emit the Uniswap V4 standardised event
        UniswapHookEvents.emitHookSwapEvent({
            _poolId: _poolId,
            _sender: _sender,
            _amount0: _tload(TS_ISP_AMOUNT0),
            _amount1: _tload(TS_ISP_AMOUNT1),
            _fee0: _tload(TS_ISP_FEE0),
            _fee1: _tload(TS_ISP_FEE1)
        });

        // @dev We flush the tstore values at this point as although they are only set
        // explicitly and not modified, both the FL and ISP could be bypassed but the tstore
        // data would remain.

        assembly {
            tstore(TS_ISP_AMOUNT0, 0)
            tstore(TS_ISP_AMOUNT1, 0)
            tstore(TS_ISP_FEE0, 0)
            tstore(TS_ISP_FEE1, 0)
            tstore(TS_UNI_AMOUNT0, 0)
            tstore(TS_UNI_AMOUNT1, 0)
            tstore(TS_UNI_FEE0, 0)
            tstore(TS_UNI_FEE1, 0)
        }
    }

    /**
     * Emits an event that provides pool state updates and passes the data to subscribers.
     *
     * @param _poolId The PoolId that has been updated
     * @param _key The selector being sent to notification subscribers
     * @param _data The data being sent to notification subscribers
     */
    function _emitPoolStateUpdate(
        PoolId _poolId,
        bytes4 _key,
        bytes memory _data
    ) internal {
        // Notify our subscribed contracts
        notifier.notifySubscribers(_poolId, _key, _data);

        // Emit our event
        (uint160 sqrtPriceX96, int24 tick, uint24 protocolFee, uint24 swapFee) = poolManager.getSlot0(_poolId);
        emit PoolStateUpdated(_poolId, sqrtPriceX96, tick, protocolFee, swapFee, poolManager.getLiquidity(_poolId));
    }

    /**
     * Settles tokens against the PoolManager based on the BalanceDelta passed.
     *
     * @dev This is required to be separated due to Stack Too Deep errors
     *
     * @param _poolKey The pool key to settle against
     * @param _delta The BalanceDelta showing token amounts to settle
     */
    function _settleDelta(
        PoolKey memory _poolKey,
        BalanceDelta _delta
    ) internal {
        if (_delta.amount0() < 0) {
            _poolKey.currency0.settle(poolManager, address(this), uint(-int(_delta.amount0())), false);
        } else if (_delta.amount0() > 0) {
            poolManager.take(_poolKey.currency0, address(this), uint(int(_delta.amount0())));
        }

        if (_delta.amount1() < 0) {
            _poolKey.currency1.settle(poolManager, address(this), uint(-int(_delta.amount1())), false);
        } else if (_delta.amount1() > 0) {
            poolManager.take(_poolKey.currency1, address(this), uint(int(_delta.amount1())));
        }
    }

    /**
     * We need to be able to set the (un)specified token to amount0 / amount1 for the expected
     * event emit format.
     *
     * @param _params The `SwapParams` used to capture the delta
     * @param _key_amount0 The tstore key for the token0 amount
     * @param _key_amount1 The tstore key for the token1 amount
     * @param _delta The `BeforeSwapDelta` that is being captured
     */
    function _captureDelta(
        SwapParams memory _params,
        bytes32 _key_amount0,
        bytes32 _key_amount1,
        BeforeSwapDelta _delta
    ) internal {
        (int token0, int token1) = _params.amountSpecified < 0 == _params.zeroForOne
            ? (-_delta.getSpecifiedDelta(), -_delta.getUnspecifiedDelta())
            : (-_delta.getUnspecifiedDelta(), -_delta.getSpecifiedDelta());

        // Store our amounts
        assembly {
            tstore(_key_amount0, token0)
            tstore(_key_amount1, token1)
        }
    }

    /**
     * Maps our swap fee to the expected event emit format.
     *
     * @param _params The `SwapParams` used to capture the delta
     * @param _key_fee0 The tstore key for the token0 fee amount
     * @param _key_fee1 The tstore key for the token1 fee amount
     * @param _delta The `uint` that is being captured for the fee
     */
    function _captureDeltaSwapFee(
        SwapParams memory _params,
        bytes32 _key_fee0,
        bytes32 _key_fee1,
        uint _delta
    ) internal {
        // The delta provided needs to be made negative
        int delta = -int(_delta);

        if (_params.amountSpecified < 0 == _params.zeroForOne) {
            assembly {
                tstore(_key_fee0, 0)
                tstore(_key_fee1, delta)
            }
        } else {
            assembly {
                tstore(_key_fee0, delta)
                tstore(_key_fee1, 0)
            }
        }
    }

    /**
     * Helper function to allow for tstore-d variables to be called individually. This saves us
     * defining an additional variable before our `tload` calls inside the function.
     *
     * @param _key The `tstore` key to load
     *
     * @return value_ The `int` value in the tstore
     */
    function _tload(
        bytes32 _key
    ) internal view returns (int value_) {
        assembly {
            value_ := tload(_key)
        }
    }
}
